---
   - name: adding php-qa repository
     apt_repository:
       repo: 'ppa:ondrej/php-qa'
     when: installed_php_version != "5.6"

   - name: adding php repository
     apt_repository:
       repo: 'ppa:ondrej/php'

   - name: Install php-fpm
     apt: name=php{{ installed_php_version }}-fpm state=latest update_cache=yes
     when: installed_php_version != "5.6" and installed_php_specific_version is not defined

   - name: Install php-common
     apt: name=php{{ installed_php_version }}-common={{ installed_php_specific_version }} state=present update_cache=yes
     when: installed_php_specific_version is defined

   - name: Install php-cli
     apt: name=php{{ installed_php_version }}-cli={{ installed_php_specific_version }} state=present update_cache=yes
     when: installed_php_specific_version is defined

   - name: Install php-fpm
     apt: name=php{{ installed_php_version }}-fpm={{ installed_php_specific_version }} state=present update_cache=yes
     when: installed_php_specific_version is defined

   - name: Install libpcre3 depedancies for php-dev (bionic)
     apt: name={{ item }} state=latest
     loop:
        - libpcrecpp0v5
        - libpcre3
        - libpcre3-dev
     when: installed_php_version != "5.6" and ansible_distribution != 'trusty'

   - name: Install libpcre3 depedancies for php-dev (trusty)
     apt: name={{ item }} state=latest
     loop:
        - libpcrecpp0
        - libpcre3
        - libpcre3-dev
     when: installed_php_version != "5.6" and ansible_distribution == 'trusty'

   - name: Install php modules
     apt: name={{ item }} state=latest
     loop: "{{ default_apt_modules + apt_modules }}"
     when: installed_php_version != "5.6" and installed_php_specific_version is not defined

   - name: Make backward compatible init script
     template: src=php-fpm.j2 dest=/etc/init.d/php-fpm mode=0755

   - name: Make backward compatible init script
     template: src=php-fpm.j2 dest=/etc/init.d/php{{ installed_php_version }}-fpm mode=0755
     when: installed_php_version != "5.6"

   - name: Copy config
     template: src={{ environment_id }}/{{ config_prefix }}/www.conf dest='/etc/php/{{ installed_php_version }}/fpm/pool.d/www.conf'
     notify:
       - restart php-fpm

   - name: Render php-cli to the right version
     shell: update-alternatives --set php /usr/bin/php{{ installed_php_version }}

   - name: Render phpize to the right version
     shell: update-alternatives --set phpize /usr/bin/phpize{{ installed_php_version }}

   - name: Render phpize to the right version
     shell: update-alternatives --set php-config /usr/bin/php-config{{ installed_php_version }}

   - name: Copy php.ini
     template: src='{{ environment_id }}/{{ config_prefix }}/php.ini' dest='/etc/php/{{ installed_php_version }}/fpm/php.ini'
     notify:
       - restart php-fpm
     when: copy_php_ini == 'yes'
